spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: order_route
          uri: lb://order-service
          predicates:
            - Path=/gper-order/**
          filters:
            - StripPrefix=1
        - id: user_route
          uri: lb://user-service
          predicates:
            - Path=/gper-user/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  redis:
    host: 192.168.216.128
    port: 6379
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.216.128:9411/
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
logging:
  level:
    root: debug