spring:
  application:
    name: goods-service
  datasource:
    url: jdbc:mysql://localhost:3306/gper_mall?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.216.128:9411/
server:
  port: 8083
mybatis:
  type-aliases-package: com.gupaoedu.goods.goodsserviceprovider.mapper.entitys

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka

logging:
  level:
    org.springframework.cloud.sleuth: debug